### ISSUE TITLE
readme中的action构建失败

### ISSUE THREAD

**Issue by shenjackyuanjie** [zjp-CN/mdbook-theme#4]
https://github.com/shenjackyuanjie/Difficult-Rocket/actions/runs/4454237547/jobs/7823292226
可以查看这里
mdbook-theme使用的是本地构建的 v0.1.2
wsl构建之后上传至release，在github action中下载

使用范例中的下载方式依然有相同问题
本地构建成功

**Comment by shenjackyuanjie** [comment]
需要注意的是
我在删除readme中范例下载方式之后成功构建
https://github.com/shenjackyuanjie/Difficult-Rocket/actions/runs/4454246016/jobs/7823305333

**Comment by shenjackyuanjie** [comment]
https://github.com/shenjackyuanjie/Minecraft_Science_Tree/releases/tag/0.0.2
本地上传的构建版本号在这里有说明

**Comment by zjp-CN** [comment]
```
Unable to parse the input
[WARN] (mdbook::preprocess::cmd): Error writing the RenderContext to the backend, Broken pipe (os error 32)
[ERROR] (mdbook::utils): Error: The "theme" preprocessor exited unsuccessfully with exit status: 1 status
```

这可能是因为 mdbook-theme 使用太旧的 mdbook 版本，我更新了所有依赖并发布了 [v0.1.3](https://github.com/zjp-CN/mdbook-theme/releases/tag/v0.1.3)，此时它是最新的 release ，无需改动 CI。

**Comment by shenjackyuanjie** [comment]
好的！
